CREATE DATABASE IF NOT EXISTS jungle_jumble;
USE jungle_jumble;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    high_score INT NOT NULL DEFAULT 0
);
